sudo: required
language: python
addons:
  firefox: latest-nightly
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
    - node_modules

before_install:
  - wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER/geckodriver-v$GECKODRIVER-linux64.tar.gz
  - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH
  - firefox --version
  - geckodriver --version

install: pip install tox
script: tox

jobs:
  include:
    - stage:
      python: 3.6
      env: TOXENV=py36 MOZ_HEADLESS=1 GECKODRIVER=0.22.0
      script: tox

    - stage:
      python: 2.7
      env: TOXENV=py27 MOZ_HEADLESS=1 GECKODRIVER=0.22.0

    - stage:
      python: 2.7
      env: TOXENV=flake8
      before_install: skip

    - stage: deploy
      before_install: skip
      install: skip
      script: skip
      skip_cleanup: true
      deploy:
        provider: pypi
        user: kimberlythegeek
        password:
          secure: LHsL91XR32/M4r5ETAvaN/vUTakYByIfdwdCw6EI59LBvSnwaSant010QIl39+uafuev57yzUC/Y+orefczjkJnG3KdQBNS0Rt/zWIMw0Dr6Fp41Vg66e5URK/FRIwK36WlWzOcd3GkrQLLaDeqnXVzDWVMuXPP9/1ssu6mvriSeLctPsmX5N6m4yZwxNtpFsTLEh+BumXiamCuqjTI0RpyqxYlUVfio0G5LWeY9rkPskrwbSbc8xhq/PMk/ecLtlAxdn8AwgjLYCAt9d6NRfgL4Yp0R+kkfUQsX1Wf8A/pBNRr8Ht8Hy4CNlnEphgao4fgVEY4dc6tZL3FXOU9jQSmbChoANlbPzDhO+nb6d/QW5vLHVDufKyRQqtFxD90XFXlWFc/0gnD6tPZhi+UEFmBMoo9ugWDnYUeBd1T3lbwKT7sOmOQS58WhDVMLxPwr2BfgItGrNsaVHmzx9v0BnxZvD5ilmvNPrad6Rcsa0N8GtNXpnbyaupWzA97bemzuLqNHOjTm6TMZWRol6lLEJsJ1MRs7xWI4DYztXzlWITH7rvf6NNyvXKe9FPV3Lfoei3k1mT8QuEh6bIEFpBKRVV0ObQVSfFQ4M4wbgDBb3CbHVqMqFHgi98mpUo9tNGm4uzZCXw3hfEQpUPugKaH+VHoaylE+MR+fOhsyVlLQluM=
        on:
          tags: true
          branch: master
          distributions: "sdist bdist_wheel"
          skip_cleanup: true

after_success:
  - pip install coveralls
  - coveralls
